graphql:
  packages:
    - "com.springboilerplate.app"

app:
  auth:
    tokenSecret: ${TOKEN_SECRET}
    tokenExpirationMsec: 1209600000
  databaseUrl: jdbc:postgresql://${DB_HOST}:5432/${DB_DATABASE}?user=${DB_USERNAME}&password=${DB_PASSWORD}

spring:
  profiles:
    active: dev
  security:
      oauth2:
        client:
          registration:
            google:
              clientId: ${GOOGLE_CLIENT_ID}
              clientSecret: ${GOOGLE_CLIENT_SECRET}
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile