app:
  redirectHost: "http://localhost:3000"
altair:
    mapping: /
    endpoint:
      graphql: /graphql
      subscriptions: /subscriptions
    subscriptions:
      timeout: 30
      reconnect: false
    static:
      basePath: "."
    enabled: true
    pageTitle: Altair
    cdn:
        enabled: false